name: dlox
description: A simple interpreted language with dart as its IR
version: 0.0.3
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3


executables:
  dlox:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  tool:
    path: tool

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  stack: ^0.2.2
