name: tool
description: Dlox tooling package
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  stack: ^0.2.2
  dlox:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
